### ISSUE TITLE
How do I fix this error?

### ISSUE THREAD

**Issue by SerCrafter22** [Vignesh9123/Spotify-clone#1]
Error fetching songs: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
getSongs                @script.js:55

await in getSongs (async)

main                       @script.js:147
(anonymous)          @script.js:190

**Comment by Vignesh9123** [comment]
You need to **download** and **enable** this extension:
https://chromewebstore.google.com/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino?pli=1
This should solve the issue
